{
 "title": "Actual Budget",
 "description": "Simple Dashboard for Actual Budget",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "budget", "label": "Budget", "query": { "query": "label_values(budget)" } }
  ]
 },
 "panels": [
  {
   "title": "Total Balance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "actual_budget_balance{budget=\"$budget\"} / 100"
    }
   ]
  },
  {
   "title": "Transactions Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "actual_budget_transaction_count{budget=\"$budget\"}"
    }
   ]
  },
  {
   "title": "Uncategorized Transactions Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "actual_budget_uncategorized_transaction_count{budget=\"$budget\"}"
    }
   ]
  },
  {
   "title": "Transactions per category",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (actual_budget_category_tranasction_count{budget=\"$budget\"})  by (category)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Balance per account",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (actual_budget_account_balance{budget=\"$budget\"} / 100)  by (account)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}