{
 "title": "OPNsense GeoIP",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Allowed incoming connections by GeoIP",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(count_over_time({hostname=\"opnsense\"} | json | appname = \"filterlog\" | filter_action = \"pass\"[$__interval])) by (geoip_country_code)",
     "legendFormat": "{{geoip_country_code}}"
    }
   ]
  },
  {
   "title": "Blocked connections by GeoIP",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(count_over_time({hostname=\"opnsense\"} | json | appname = \"filterlog\" | filter_interface = \"igc0\" | filter_action = \"block\"[$__interval])) by (geoip_country_code)",
     "legendFormat": "{{geoip_country_code}}"
    }
   ]
  },
  {
   "title": "Top 10 allowed incoming ports",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, \n  sum by (filter_destination_port) (\n  count_over_time(\n      {hostname=\"opnsense\"} \n      | json \n      | appname = \"filterlog\"\n      | filter_destination_port != \"\"\n      | filter_action = \"pass\"\n      | filter_interface = \"igc0\"\n      [$__range]\n    )\n  )\n)",
     "legendFormat": "{{filter_destination_port}}"
    }
   ]
  },
  {
   "title": "Top 10 blocked countries",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, \n  sum by (geoip_country_name) (\n  count_over_time(\n      {hostname=\"opnsense\"} \n      | json \n      | appname = \"filterlog\"\n      | filter_source_ip != \"\"\n      | filter_action = \"block\"\n      | filter_interface = \"igc0\"\n      [$__range]\n    )\n  )\n)",
     "legendFormat": "{{geoip_country_name}}"
    }
   ]
  }
 ]
}